// ===================== HELPERS (tech props + text widgets) =====================
// needs premium.js (P, S, wtext). chipM uses url(#gCore): rgrad(defs, 'gCore', col, .45) first.
// short colour names (quantization video): full precision blue, quantized green, scale amber, bad red, model purple
function funnelG(par, cx, cy, size, col) { const k = size / 100; return S('path', { d: `M${cx - 42 * k} ${cy - 38 * k} L${cx + 42 * k} ${cy - 38 * k} L${cx + 8 * k} ${cy + 2 * k} L${cx + 8 * k} ${cy + 36 * k} L${cx - 8 * k} ${cy + 44 * k} L${cx - 8 * k} ${cy + 2 * k} Z`, fill: col }, par); }
const FP = P.ctx, QZ = P.emb, SC = P.tgt, BAD = P.bad, MOD = P.pred;
function chipM(par, cx, cy, s, col, id) { const g = S('g', { id }, par); S('circle', { cx, cy, r: 260 * s, fill: 'url(#gCore)' }, g);
  for (let k = 0; k < 4; k++) { const o = (k - 1.5) * 56 * s; [[cx - 190 * s, cy + o - 8 * s, 40 * s, 16 * s], [cx + 150 * s, cy + o - 8 * s, 40 * s, 16 * s], [cx + o - 8 * s, cy - 170 * s, 16 * s, 40 * s], [cx + o - 8 * s, cy + 130 * s, 16 * s, 40 * s]].forEach(([x, y, w, h]) => S('rect', { x, y, width: w, height: h, rx: 4 * s, fill: col, opacity: .7 }, g)); }
  S('rect', { x: cx - 160 * s, y: cy - 140 * s, width: 320 * s, height: 280 * s, rx: 44 * s, fill: '#120d2a', stroke: col, 'stroke-width': 7 * s }, g); nnet(g, cx, cy, 210 * s, 170 * s, [3, 4, 4, 3], col, id + 'N'); return g; }
function block(par, x, y, w, h, col, label, id, fs) { const g = S('g', { id }, par); S('rect', { x, y, width: w, height: h, rx: 22, fill: col, 'fill-opacity': .25, stroke: col, 'stroke-width': 6 }, g);
  for (let r = 0; r < Math.floor((h - 30) / 34); r++) for (let c = 0; c < Math.floor((w - 30) / 34); c++) S('rect', { x: x + 18 + c * 34, y: y + 18 + r * 34, width: 26, height: 26, rx: 5, fill: col, opacity: .18 + .5 * rnd(r * 31 + c) }, g);
  if (label) { S('rect', { x: x + w / 2 - (label.length * (fs || 50) * .32 + 30), y: y + h / 2 - (fs || 50) * .75, width: label.length * (fs || 50) * .64 + 60, height: (fs || 50) * 1.5, rx: 18, fill: '#0b1020', opacity: .85 }, g); wtext(g, x + w / 2, y + h / 2 + (fs || 50) * .36, label, fs || 50, '#f8fafc'); } return g; }
function gpu(par, x, y, s, id) { const g = S('g', { id }, par); S('rect', { x, y, width: 420 * s, height: 190 * s, rx: 18 * s, fill: '#1f2937', stroke: '#64748b', 'stroke-width': 5 }, g); [0, 1].forEach(k => { const cx = x + (110 + k * 200) * s, cy = y + 95 * s; S('circle', { cx, cy, r: 70 * s, fill: '#111827', stroke: '#475569', 'stroke-width': 5 }, g); for (let b = 0; b < 6; b++) S('path', { d: `M${cx} ${cy} L${cx + Math.cos(b * 1.05) * 60 * s} ${cy + Math.sin(b * 1.05) * 60 * s}`, stroke: '#64748b', 'stroke-width': 10 * s, 'stroke-linecap': 'round' }, g); }); S('rect', { x: x + 40 * s, y: y + 190 * s, width: 300 * s, height: 22 * s, rx: 4, fill: '#ca8a04' }, g); return g; }
function laptop(par, x, y, s, id) { const g = S('g', { id }, par); S('rect', { x, y, width: 420 * s, height: 270 * s, rx: 18 * s, fill: '#1f2937', stroke: '#94a3b8', 'stroke-width': 6 }, g); S('rect', { x: x + 22 * s, y: y + 22 * s, width: 376 * s, height: 226 * s, rx: 8, fill: '#0b1226' }, g); S('path', { d: `M${x - 40 * s} ${y + 290 * s} L${x + 460 * s} ${y + 290 * s} L${x + 430 * s} ${y + 320 * s} L${x - 10 * s} ${y + 320 * s} Z`, fill: '#94a3b8' }, g); return g; }
function phone(par, x, y, s, id) { const g = S('g', { id }, par); S('rect', { x, y, width: 180 * s, height: 340 * s, rx: 30 * s, fill: '#1f2937', stroke: '#94a3b8', 'stroke-width': 6 }, g); S('rect', { x: x + 14 * s, y: y + 34 * s, width: 152 * s, height: 270 * s, rx: 10, fill: '#0b1226' }, g); S('rect', { x: x + 66 * s, y: y + 14 * s, width: 48 * s, height: 8 * s, rx: 4, fill: '#475569' }, g); return g; }
function server(par, x, y, s, id) { const g = S('g', { id }, par); S('rect', { x, y, width: 300 * s, height: 520 * s, rx: 16 * s, fill: '#111827', stroke: '#64748b', 'stroke-width': 5 }, g); for (let k = 0; k < 7; k++) { S('rect', { x: x + 20 * s, y: y + 22 * s + k * 70 * s, width: 260 * s, height: 54 * s, rx: 8, fill: '#1f2937' }, g); S('circle', { class: 'srvL', cx: x + 250 * s, cy: y + 49 * s + k * 70 * s, r: 7 * s, fill: k % 3 ? QZ : SC }, g); } return g; }
function desktop(par, x, y, s, id) { const g = S('g', { id }, par); S('rect', { x, y, width: 380 * s, height: 250 * s, rx: 14 * s, fill: '#1f2937', stroke: '#94a3b8', 'stroke-width': 6 }, g); S('rect', { x: x + 18 * s, y: y + 18 * s, width: 344 * s, height: 214 * s, rx: 6, fill: '#0b1226' }, g); S('rect', { x: x + 170 * s, y: y + 250 * s, width: 40 * s, height: 60 * s, fill: '#64748b' }, g); S('rect', { x: x + 110 * s, y: y + 305 * s, width: 160 * s, height: 16 * s, rx: 6, fill: '#64748b' }, g); S('rect', { x: x + 420 * s, y: y - 20 * s, width: 140 * s, height: 340 * s, rx: 14 * s, fill: '#1f2937', stroke: '#94a3b8', 'stroke-width': 6 }, g); [0, 1, 2].forEach(k => S('rect', { x: x + 440 * s, y: y + 10 * s + k * 34 * s, width: 100 * s, height: 20 * s, rx: 4, fill: '#334155' }, g)); return g; }
function okM(par, cx, cy, r, id) { const g = S('g', { id }, par); S('circle', { cx, cy, r, fill: QZ }, g); S('path', { d: `M${cx - r * .45} ${cy + r * .02} L${cx - r * .1} ${cy + r * .38} L${cx + r * .5} ${cy - r * .38}`, stroke: '#052e1f', 'stroke-width': r * .22, fill: 'none', 'stroke-linecap': 'round' }, g); return g; }
function noWifi(par, cx, cy, s, id) { const g = S('g', { id }, par); [1, .66, .33].forEach(f => S('path', { d: `M${cx - 60 * s * f} ${cy - 10 * s * f} Q${cx} ${cy - 70 * s * f} ${cx + 60 * s * f} ${cy - 10 * s * f}`, stroke: '#94a3b8', 'stroke-width': 9 * s, fill: 'none', 'stroke-linecap': 'round' }, g)); S('circle', { cx, cy: cy + 10 * s, r: 9 * s, fill: '#94a3b8' }, g); S('path', { d: `M${cx - 60 * s} ${cy + 30 * s} L${cx + 60 * s} ${cy - 80 * s}`, stroke: BAD, 'stroke-width': 10 * s, 'stroke-linecap': 'round' }, g); return g; }
function bits(par, x, y, n, c, col, id, vals) { const g = S('g', { id }, par); for (let k = 0; k < n; k++) { const b = S('g', { id: id + k }, g); S('rect', { x: x + k * (c + 8), y, width: c, height: c * 1.25, rx: 10, fill: col, 'fill-opacity': .22, stroke: col, 'stroke-width': 4 }, b); wtext(b, x + k * (c + 8) + c / 2, y + c * .85, vals ? vals[k] : String(Math.round(rnd(k + 7))), c * .55, '#f8fafc', 'middle', 700); } return g; }
function nline(par, x0, x1, y, col, id, w = 6) { return S('path', { id, class: 'draw', d: `M${x0} ${y} L${x1} ${y}`, stroke: col, 'stroke-width': w, 'stroke-linecap': 'round' }, par); }
function ticks(par, x0, x1, y, n, h, col, id, w = 4) { const g = S('g', { id }, par); for (let k = 0; k < n; k++) { const x = x0 + (x1 - x0) * k / (n - 1); S('path', { d: `M${x} ${y - h} L${x} ${y + h}`, stroke: col, 'stroke-width': w, 'stroke-linecap': 'round' }, g); } return g; }
// ---- text widgets & model chip (agents video) ----
function brainBox(par, cx, cy, s, id, col = '#a78bfa') {   // needs rgrad(defs, 'gMod', col, .45); neuron dots class id+'Ng'+layer -> fire(id+'N', 4, t, gap, 3)   // the language model: glowing violet chip with a brain + text-lines mouth
  const g = S('g', { id }, par); S('circle', { cx, cy, r: 280 * s, fill: 'url(#gMod)' }, g);
  for (let k = 0; k < 4; k++) { const o = (k - 1.5) * 56 * s; [[cx - 190 * s, cy + o - 8 * s, 40 * s, 16 * s], [cx + 150 * s, cy + o - 8 * s, 40 * s, 16 * s], [cx + o - 8 * s, cy - 170 * s, 16 * s, 40 * s], [cx + o - 8 * s, cy + 130 * s, 16 * s, 40 * s]].forEach(([x, y, w, h]) => S('rect', { x, y, width: w, height: h, rx: 4 * s, fill: col, opacity: .75 }, g)); }
  S('rect', { x: cx - 160 * s, y: cy - 140 * s, width: 320 * s, height: 280 * s, rx: 44 * s, fill: '#1a1033', stroke: col, 'stroke-width': 8 * s }, g);
  ic(g, 'brain', cx, cy - 20 * s, 170 * s, '#c4b5fd'); [0, 1, 2].forEach(k => S('rect', { class: id + 'L', x: cx - 70 * s, y: cy + 80 * s + k * 0, width: 140 * s, height: 0, rx: 4, fill: '#38bdf8' }, g));
  for (let li = 0; li < 4; li++) [-1, 1].forEach(sg => S('circle', { class: id + 'Ng' + li, cx: cx + (li - 1.5) * 52 * s, cy: cy - 20 * s + sg * (li % 2 ? 46 : 26) * s, r: 11 * s, fill: '#fde68a', opacity: .15 }, g));
  return g; }
function tln(par, x, y, txt, fs, col, cls, anchor = 'start', mono = true, w = 700) { const t = S('text', Object.assign({ x, y, 'font-size': fs, 'font-weight': w, fill: col, 'text-anchor': anchor, 'font-family': mono ? 'JetBrains Mono, monospace' : 'Poppins' }, cls ? { class: cls } : {}), par); t.textContent = txt; return t; }
function chat(par, x, y, w, h, col, id, fg, txt, fs = 34, tail = 'l') { const g = S('g', { id, filter: 'url(#fSh)' }, par); S('rect', { x, y, width: w, height: h, rx: 24, fill: col }, g); S('path', { d: tail === 'l' ? `M${x + 30} ${y + h - 4} L${x + 10} ${y + h + 36} L${x + 70} ${y + h - 4} Z` : `M${x + w - 70} ${y + h - 4} L${x + w - 10} ${y + h + 36} L${x + w - 30} ${y + h - 4} Z`, fill: col }, g); if (txt) wtext(g, x + w / 2, y + h / 2 + fs * .36, txt, fs, fg || '#0b1020', 'middle', 700); return g; }
function codeCard(par, x, y, w, lines, col, id, fs = 30) { const h = 40 + lines.length * fs * 1.45; const g = S('g', { id, filter: 'url(#fSh)' }, par); S('rect', { x, y, width: w, height: h, rx: 18, fill: '#0b1020', stroke: col, 'stroke-width': 5 }, g); lines.forEach(([t, c], k) => { const tt = S('text', { x: x + 28, y: y + 24 + fs + k * fs * 1.45, 'font-size': fs, 'font-family': 'JetBrains Mono, monospace', 'font-weight': 700, fill: c || '#e8eefc' }, g); tt.textContent = t; }); return g; }
function gearG(par, cx, cy, s, col, id) { const g = S('g', { id }, par); ic(g, 'gear', cx, cy, 120 * s, col); return g; }
function win(par, x, y, w, h, col, id) { const g = S('g', { id, filter: 'url(#fSh)' }, par); S('rect', { x, y, width: w, height: h, rx: 14, fill: '#f8fafc' }, g); S('rect', { x, y, width: w, height: 34, rx: 14, fill: col }, g); [0, 1, 2].forEach(k => S('circle', { cx: x + 22 + k * 20, cy: y + 17, r: 6, fill: '#0b1020', opacity: .35 }, g)); [0, 1, 2, 3].forEach(r => S('rect', { x: x + 20, y: y + 56 + r * 26, width: (w - 40) * [1, .8, .9, .6][r], height: 12, rx: 6, fill: '#cbd5e1' }, g)); return g; }
